---
env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
- plugin:import/errors
- plugin:import/warnings
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  no-const-assign: warn
  no-this-before-super: warn
  no-undef: warn
  no-unreachable: warn
  no-unused-vars: warn
  constructor-super: warn
  valid-typeof: warn
